blank_issues_enabled: false
contact_links:
  - name: Install 100xBot
    url: https://chromewebstore.google.com/detail/100xbot/kipkglfnhnpbogckhlmikjlfpbngnioc
    about: Install 100xBot from the Chrome Web Store
  - name: GitHub Discussions
    url: https://github.com/100x-bot/100xbot/discussions
    about: Ask questions and discuss with the community
